# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preview',
            field=models.TextField(default='', help_text='Preview for recipe thumbnails, maximum 150 characters',
                                   verbose_name='Preview'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(verbose_name='Recipe text'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='recipe', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
