version: "3.9"
name: "vcelnice-builder"
services:
  box:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=vcelnice.settings.production