# Generated by Django 2.0 on 2018-04-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_auto_20180109_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
