# Generated by Django 6.0.3 on 2026-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_reservation_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AddField(
            model_name='price',
            name='amount_description',
            field=models.CharField(blank=True, help_text='Description of amount for reservation, e.g. Number of glasses', max_length=100, null=True, verbose_name='Amount description'),
        ),
        migrations.AddField(
            model_name='price',
            name='in_store',
            field=models.IntegerField(default=0, verbose_name='In store'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='image',
            field=models.ImageField(upload_to='prices/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='price',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
    ]
