# Generated by Django 2.0 on 2018-01-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='visitor',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='body',
            new_name='message',
        ),
    ]
