# Generated by Django 2.0 on 2019-07-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPhoneNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'phone number',
                'verbose_name_plural': 'phone numbers',
            },
        ),
        migrations.AlterModelOptions(
            name='contactaddress',
            options={'verbose_name': 'Contact address', 'verbose_name_plural': 'Contact addresses'},
        ),
    ]
