name: "vcelnice-builder"
services:
  box:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ..:/app
    environment:
      - DJANGO_SETTINGS_MODULE=vcelnice.settings.production