# Generated by Django 6.1.1 on 2026-10-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200111_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Certificate',
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
    ]
