# Generated by Django 2.0 on 2018-03-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Body')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'Home text',
                'verbose_name_plural': 'Home text',
            },
        ),
    ]
