"""
Django settings for vcelnice project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
from pathlib import Path
from time import strftime
import os

BASE_DIR = Path(__file__).resolve().parents[2]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd-!60ogu)$*z6i9f%q0f!&&6fjf@vf+stci2r5i=22-mkvaea8'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'django_ckeditor_5',
    'rest_framework',

    # My apps
    'contact.apps.ContactConfig',
    'documents.apps.DocumentsConfig',
    'home.apps.HomeConfig',
    'news.apps.NewsConfig',
    'photo.apps.PhotoConfig',
    'prices.apps.PricesConfig',
    'recipe.apps.RecipeConfig',
    'video.apps.VideoConfig',
    # The region page is served by the SPA, so the legacy Django app stays uninstalled.
]

LANGUAGE_COOKIE_NAME = 'cs'

# Logging info:
# https://docs.python.org/2/library/logging.html#formatter-objects
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': 'LOG:%(levelname)s TIME: %(asctime)s MESSAGE: %(message)s PATHNAME: %(pathname)s'
        }
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue'
        }
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / f"debug_{strftime('%Y_%m_%d')}.log",
            'formatter': 'verbose',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'vcelnice.info': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'staticfiles' / 'client',
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'cs'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
CLIENT_DIST_DIR = BASE_DIR / "client" / "dist"
STATICFILES_DIRS = [("client", CLIENT_DIST_DIR)] if CLIENT_DIST_DIR.is_dir() else []
LOGS_DIR = BASE_DIR / "logs"

MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get("DJANGO_MEDIA_ROOT", BASE_DIR / 'media'))

LOCALE_PATHS = [BASE_DIR / 'locale']

DJANGO_WYSIWYG_FLAVOR = 'ckeditor'
DJANGO_WYSIWYG_MEDIA_URL = '//cdn.ckeditor.com/4.5.6/full/'

X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

ADMIN_EMAIL_ADDRESS = 'Oleg Yapparov <oyapparov@gmail.com>'
SENDER_EMAIL_ADDRESS = 'vcelnicerudna@gmail.com'
SENDER_EMAIL_NAME = 'Včelnice Rudná'

CKEDITOR_5_CONFIGS = {
    "extends": {
        "language": "cs",
        "toolbar": [
            "undo", "redo",
            "|",
            "bold", "italic", "underline",
            "|",
            "link",
            "|",
            "bulletedList", "numberedList",
            "|",
            "outdent", "indent",
            "|",
            "blockQuote",
            "|",
            "insertTable",
            "|",
            "alignment",
            "|",
            "removeFormat",
        ],
    },
}
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"
