# Generated by Django 6.0.3 on 2026-09-13

import django.core.validators
from django.db import migrations, models


def check_hidden_video_links(apps, schema_editor):
    video = apps.get_model('video', 'Video')
    hidden_links = video.objects.using(schema_editor.connection.alias).filter(
        models.Q(youtube_status__isnull=True) | models.Q(youtube_status__lte=1)
    ).exclude(youtube_id__isnull=True).exclude(youtube_id='')
    if hidden_links.exists():
        raise RuntimeError(
            'Some hidden videos already have a YouTube ID. Review these records before migrating: '
            'clear their ID to keep them hidden, or mark them as uploaded in the old data only if '
            'they should be public. Back up the database first; no video IDs have been changed.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20200111_2302'),
    ]

    operations = [
        migrations.RunPython(check_hidden_video_links, migrations.RunPython.noop),
        migrations.DeleteModel(name='VideoCategory'),
        migrations.RemoveField(model_name='video', name='category'),
        migrations.RemoveField(model_name='video', name='tags'),
        migrations.RemoveField(model_name='video', name='youtube_status'),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, max_length=150, upload_to='youtube', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name='YouTube video ID',
                help_text='Upload the video to YouTube manually and enter its 11-character ID, not the full URL. '
                          'Leave blank to hide the video from the website.',
                validators=[django.core.validators.RegexValidator(
                    message='Enter a valid 11-character YouTube video ID.', regex=r'\A[a-zA-Z0-9_-]{11}\Z',
                )],
            ),
        ),
    ]
