# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photo/')),
                ('thumb', models.ImageField(upload_to='photo/thumb/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
